import json, os, subprocess, zipfile
from pathlib import Path
from playwright.sync_api import sync_playwright
root=Path(__file__).resolve().parents[1]; out=Path(os.environ.get('COMPAT_REVIEW_DIR',str(root/'build'/'compatibility-review')));out.mkdir(parents=True,exist_ok=True)
err=open(out/'backend-errors.log','w')
server=subprocess.Popen(['node','test/compatibility/browser-host.cjs'],cwd=root,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=err,text=True,env={**os.environ,'COMPAT_TEST_OUTPUT':str(out)})
checks=[]
def rpc(method,data):
    server.stdin.write(json.dumps({'method':method,'data':data})+'\n');server.stdin.flush()
    result=server.stdout.readline()
    if not result: raise RuntimeError('backend exited')
    return json.loads(result)
def check(label,yes=True):
    assert yes,label;checks.append(label)
try:
  with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
    page=browser.new_page(viewport={'width':1180,'height':780}); errors=[]; requests=[]
    page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
    page.set_content('''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"></head><body><main><p class="eyebrow">装机宅 DLSS5 · 界面隔离测试</p><h1>示例游戏</h1><div class="game-card"><div class="gp-inline" id="host"></div></div></main></body></html>''')
    page.add_style_tag(content='''*{box-sizing:border-box}body{margin:0;background:#0c0e10;color:#e4e7e9;font:15px/1.55 "Noto Sans CJK SC",sans-serif}main{max-width:1020px;margin:auto;padding:24px}.eyebrow{color:#99a4ad;font-size:12px}h1{font-size:24px}h3{font-size:17px}.gp-section{background:#15191d;border:1px solid #2c343c;padding:20px;border-radius:12px;margin:12px 0}.gp-controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.gp-field{display:grid;gap:8px;min-width:0}.gp-field span{font-weight:600}.gp-range{display:flex;gap:12px}.gp-range input{flex:1;min-width:0}select{font:inherit;color:inherit;background:#20262b;border:1px solid #46515a;border-radius:8px;padding:9px}.gp-apply-bar{display:flex;justify-content:space-between;align-items:center}.button{font:inherit;padding:9px 20px;border:1px solid #586770;border-radius:8px;background:#252c33;color:#e4e7e9}.primary{background:#83dd97;color:#092411}.fixture-tabs{margin:20px 0;padding-bottom:12px;border-bottom:1px solid #36414b}.gp-nr-details summary{cursor:pointer;margin:12px 0}.cx-context-game{font-weight:700;color:#bcdfc4}@media(max-width:500px){main{padding:14px}.gp-controls{grid-template-columns:1fr}}''')
    page.add_style_tag(content=(root/'src/renderer/compatibility-panel.css').read_text())
    page.expose_function('reportingHost',rpc)
    page.add_script_tag(content=(root/'test/compatibility/browser-fixture.js').read_text())
    page.add_script_tag(content=(root/'src/renderer/compatibility-panel.js').read_text())
    page.add_script_tag(content=(root/'src/renderer/compatibility-integration.js').read_text())
    page.evaluate('''async()=>{window.ui=GamePageUi.mount(document.querySelector('#host'),fixtureManager);await ui.open('sample');}''')
    page.get_by_role('button',name='反馈本次体验').wait_for()
    check('original host and controller retained',page.evaluate('originalMounts[0]===document.querySelector("#host") && ui.originalAction()==="preserved" && GamePageUi.marker==="original-unchanged"'))
    check('style and model strength are the only general first-screen controls',page.locator('.gp-nr-primary [data-gp-field]').evaluate_all('(e)=>e.map(x=>x.dataset.gpField)')==['Style','Intensity'])
    check('advanced NR controls remain available without duplicating them',page.locator('[data-gp-field=LocalToneStrength]').count()==1 and not page.locator('[data-gp-field=LocalToneStrength]').is_visible())
    check('simple caption replaces jargon',page.get_by_text('增强版本',exact=True).is_visible())
    check('original primary action is not duplicated',page.locator('#host .primary').count()==1)
    check('no extra recipe picker is added',page.locator('.cx-compact details').count()==0)
    page.locator('[data-gp-field=Style]').select_option('2')
    check('original delegated event updates its draft',page.evaluate('ui.getState().draft.Style')=='2')
    page.get_by_text('细节、性能与更多设置',exact=True).click()
    check('advanced controls can be expanded',page.locator('[data-gp-field=LocalToneStrength]').is_visible())
    page.evaluate('ui.refresh()');page.wait_for_timeout(40)
    check('original details expansion survives rerender',page.locator('.gp-nr-details').evaluate('(x)=>x.open'))
    page.get_by_text('细节、性能与更多设置',exact=True).click()
    page.screenshot(path=str(out/'01-simple-game-controls.png'),full_page=True)
    check('readable non-success status', '文件已安装' in page.locator('.cx-status').inner_text())
    page.evaluate('window.mutations=0;window.counter=new MutationObserver(r=>mutations+=r.length);counter.observe(document.querySelector("#host"),{childList:true,subtree:true});')
    page.wait_for_timeout(120);first=page.evaluate('mutations');page.wait_for_timeout(180)
    check('no MutationObserver idle loop',page.evaluate('mutations')==first)
    page.evaluate('ui.setBusy(true)');page.wait_for_timeout(40)
    check('report action disabled during existing mutation',page.get_by_role('button',name='反馈本次体验').is_disabled())
    page.evaluate('ui.setBusy(false)');page.wait_for_timeout(40)
    page.get_by_role('button',name='反馈本次体验').click()
    check('native modal mounted outside rerendered card',page.locator('body > dialog').count()==1 and page.locator('dialog').evaluate('(e)=>e.open'))
    check('current game identity visible in survey',page.locator('.cx-context-game').inner_text()=='示例游戏 · 隔离测试')
    check('all three choices initially uncertain',page.locator('input[type=radio]:checked').evaluate_all('(e)=>e.map(x=>x.value)')==['unknown']*3)
    check('logs remain opt in',not page.locator('[name=includeLogs]').is_checked())
    page.get_by_text('正常',exact=True).click();page.get_by_text('有异常',exact=True).click();page.get_by_label('闪烁',exact=True).check()
    page.get_by_text('勉强可用',exact=True).click();page.locator('textarea').fill('读档后闪烁，切回原版恢复正常。')
    page.evaluate('ui.refresh()');page.wait_for_timeout(40)
    check('refresh does not close or reset feedback modal',page.locator('dialog').evaluate('(x)=>x.open') and page.locator('textarea').input_value().startswith('读档'))
    page.screenshot(path=str(out/'02-three-ratings.png'),full_page=True)
    page.get_by_role('button',name='预览反馈包').click();page.get_by_role('button',name='确认并保存反馈包').wait_for()
    check('manual snapshot is disclosed in actual adapter preview','当前配置快照' in page.locator('.cx-summary').first.inner_text())
    check('driver is automatically in report','32.0.15.6107' in page.locator('.cx-summary').first.inner_text())
    check('no display success inferred','未确认' in page.locator('.cx-summary').first.inner_text() or 'unknown' in page.locator('.cx-summary').first.inner_text())
    page.get_by_role('button',name='返回修改').click()
    check('return to editing retains choices',page.locator('input[name=image][value=artifacts]').is_checked())
    page.locator('[name=includeLogs]').check();page.get_by_role('button',name='预览反馈包').click();page.get_by_role('button',name='确认并保存反馈包').wait_for()
    check('historical log is explicitly not current proof','历史附件' in page.locator('dialog').text_content())
    check('log does not leak sample user path','C:\\Users\\example' not in page.locator('.cx-log').text_content())
    page.screenshot(path=str(out/'03-package-preview.png'),full_page=True)
    page.get_by_role('button',name='确认并保存反馈包').click();page.get_by_text('反馈包已保存。请将 ZIP 发给测试群管理员。').wait_for()
    files=list(out.glob('compat-*.zip'));check('actual ZIP written by integrated adapter',bool(files))
    with zipfile.ZipFile(max(files,key=lambda p:p.stat().st_mtime)) as z:
      check('Python independently validates ZIP CRC',z.testzip() is None)
      report=json.loads(z.read('report.json'));check('saved subjective score retained',report['ratings']['image']=='artifacts')
      check('observations remain unknown without launch match',report['outcome']['stages']['nr']['state']=='unknown')
    check('modal closed on real save receipt',not page.locator('dialog').evaluate('(x)=>x.open'))
    for width,height in [(900,620),(390,844)]:
      page.set_viewport_size({'width':width,'height':height});page.get_by_role('button',name='反馈本次体验').click()
      check(f'{width} modal no horizontal overflow',page.locator('dialog').evaluate('(e)=>e.scrollWidth<=e.clientWidth+1'))
      check(f'{width} primary button visible',page.get_by_role('button',name='预览反馈包').evaluate('(e)=>{let r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}'))
      page.screenshot(path=str(out/f'04-survey-{width}.png'),full_page=True);page.keyboard.press('Escape')
      check(f'{width} Escape closes idle modal',not page.locator('dialog').evaluate('(x)=>x.open'))
    page.set_viewport_size({'width':1180,'height':780});page.get_by_role('button',name='反馈本次体验').click()
    page.locator('textarea').fill('旧游戏备注');page.evaluate('ui.open("different")');page.wait_for_timeout(40)
    check('switching game closes prior modal',not page.locator('dialog').evaluate('(x)=>x.open'))
    page.evaluate('ui.dispose()');page.wait_for_timeout(40)
    check('dispose removes observer/footer/dialog and old view',page.locator('dialog').count()==0 and page.locator('#host').inner_text()=='')
    check('no browser errors',not errors);check('no network request from UI',not requests)
    browser.close()
  result={'passed':len(checks),'scope':'New actual UI/048 adapter + Node host; existing game controller and hardware mocked. Not full Electron/Windows/game acceptance.','checks':checks}
  (out/'results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2));print(json.dumps(result,ensure_ascii=False))
finally:
  server.terminate()
  try:server.wait(timeout=3)
  except subprocess.TimeoutExpired:server.kill()
  err.close()
