'use strict';

const { contextBridge, ipcRenderer, webUtils } = require('electron');

const invoke = (name, ...args) => ipcRenderer.invoke(name, ...args);
contextBridge.exposeInMainWorld('manager', Object.freeze({
  startupReady: () => ipcRenderer.send('startup-renderer-ready'),
  startupFailed: message => ipcRenderer.send('startup-renderer-failed', String(message || '').slice(0, 500)),
  exportStartupDiagnostic: () => invoke('startup-export'),
  getStartupContext: () => invoke('startup-context'),
  inspectOperationElevation: () => invoke('operation-elevation-inspect'),
  recoverOperationElevation: request => invoke('operation-elevation-recover', request),
  boot: () => invoke('boot'),
  listComponents: () => invoke('components-list'),
  inspectComponentProviders: () => invoke('components-providers'),
  selectComponentProvider: id => invoke('components-provider-select', id),
  pickComponent: directory => invoke('components-pick', directory === true),
  pickRuntimeDlc: () => invoke('components-runtime-pick'),
  activateComponentRuntime: id => invoke('components-runtime-activate', id),
  activateComponentCore: id => invoke('components-core-activate', id),
  moveComponentLibrary: () => invoke('components-storage-pick'),
  componentChoices: id => invoke('game-components', id),
  setUserAddon: (id, componentId, enabled) => invoke('game-user-addon-set', id, componentId, enabled === true),
  checkComponentUpdates: () => invoke('components-updates'),
  downloadComponent: id => invoke('components-download', id),
  checkManagerUpdate: () => invoke('manager-update-check'),
  prepareManagerUpdate: manifest => invoke('manager-update-prepare', manifest),
  cancelManagerUpdate: () => invoke('manager-update-cancel'),
  applyManagerUpdate: () => invoke('manager-update-apply'),
  onManagerUpdateProgress: callback => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('manager-update-progress', listener);
    return () => ipcRenderer.removeListener('manager-update-progress', listener);
  },
  applyBridgeComponent: (id, bridge) => invoke('game-component-apply', id, bridge),
  refresh: () => invoke('games-refresh'),
  listGames: () => invoke('games-list'),
  assessGame: (id, options) => invoke('game-assessment', id, options),
  recordVisualComparison: (id, input) => invoke('game-visual-record', id, input),
  previewOperation: (id, request) => invoke('game-operation-preview', id, request),
  applyOperation: (id, planId, consent) => invoke('game-operation-apply', id, planId, consent),
  applyOperationElevated: (id, planId, consent) => invoke('game-operation-apply-elevated', id, planId, consent),
  recoverOperation: id => invoke('game-operation-recover', id),
  confirmGameFeature: (id, domain, value) => invoke('game-feature-confirm', id, domain, value),
  inspectLaunchSession: id => invoke('game-launch-session', id),
  cancelLaunch: id => invoke('game-launch-cancel', id),
  onLaunchSession: callback => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('launch-session-updated', listener);
    return () => ipcRenderer.removeListener('launch-session-updated', listener);
  },
  pickGame: () => invoke('pick-game'),
  pickExecutable: () => invoke('pick-executable'),
  pickHoYoLauncher: () => invoke('pick-hoyo-launcher'),
  hoyoDiscover: () => invoke('hoyo-discover'),
  hoyoInspect: (id, options) => invoke('hoyo-inspect', id, options),
  hoyoPickGame: () => invoke('hoyo-pick-game'),
  hoyoPickLauncher: id => invoke('hoyo-pick-launcher', id),
  hoyoBind: (id, input) => invoke('hoyo-bind', id, input),
  hoyoPreview: (id, action, options) => invoke('hoyo-preview', id, action, options),
  hoyoApply: (id, planId, consent) => invoke('hoyo-apply', id, planId, consent),
  hoyoRecover: id => invoke('hoyo-recover', id),
  hoyoStart: id => invoke('hoyo-start', id),
  hoyoCancel: id => invoke('hoyo-cancel', id),
  pickAddon: () => invoke('pick-addon'),
  pickScanFolder: () => invoke('pick-scan-folder'),
  install: (id, options) => invoke('game-install', id, options),
  launch: id => invoke('game-launch', id),
  repair: (id, options) => invoke('game-repair', id, options),
  upgradeAddon: (id, version, options) => invoke('game-upgrade-addon', id, version, options),
  dismissGame: id => invoke('game-dismiss', id),
  removeGame: (id, options) => options === undefined ? invoke('game-library-remove', id) : invoke('game-library-remove', id, options),
  previewDeploymentRescue: (id, mode = 'repair') => invoke('game-deployment-rescue-preview', id, mode),
  applyDeploymentRescue: (id, planId, consent) => invoke('game-deployment-rescue-apply', id, planId, consent),
  renameGame: (id, name) => invoke('game-rename', id, name),
  setGameApi: (id, api, options) => invoke('game-api-set', id, api, options),
  setGameApiPreference: (id, api) => invoke('game-api-preference', id, api),
  requestOperation: (id, request, consent) => invoke('game-operation-submit', id, request, consent),
  cancelWaitingOperation: id => invoke('game-operation-cancel-waiting', id),
  onWaitingOperation: callback => {
    const listener = (_event, value) => callback(value);
    ipcRenderer.on('waiting-operation-updated', listener);
    return () => ipcRenderer.removeListener('waiting-operation-updated', listener);
  },
  onOperationProgress: callback => {
    const listener = (_event, value) => callback(value);
    ipcRenderer.on('operation-progress', listener);
    return () => ipcRenderer.removeListener('operation-progress', listener);
  },
  applyGameRoute: (id, options) => invoke('game-route-apply', id, options),
  prepareGame: (id, options) => invoke('game-prepare-all', id, options),
  inspectPreparation: id => invoke('game-preparation-inspect', id),
  inspectEnvironment: id => invoke('game-environment-inspect', id),
  prepareEnvironmentCleanup: id => invoke('game-environment-prepare-clean', id),
  previewEnvironmentCleanup: id => invoke('game-environment-preview-clean', id),
  applyEnvironmentCleanup: (id, planId, names) => invoke('game-environment-apply', id, planId, names),
  restoreEnvironment: id => invoke('game-environment-restore', id),
  recoverPreparation: id => invoke('game-preparation-recover', id),
  inspectFeeder: id => invoke('game-feeder-inspect', id),
  installFeeder: (id, options) => invoke('game-feeder-install', id, options),
  restoreFeeder: id => invoke('game-feeder-restore', id),
  toggleD3D12: (id, enabled, options) => invoke('game-toggle-d3d12', id, enabled, options),
  uninstall: (id, removeSettings = false) => invoke('game-uninstall', id, removeSettings),
  diagnose: id => invoke('game-diagnose', id),
  openCompatibilityFeedback: id => invoke('compatibility-open', id),
  previewCompatibilityFeedback: (token, request) => invoke('compatibility-preview', token, request),
  saveCompatibilityFeedback: (token, request) => invoke('compatibility-save', token, request),
  discardCompatibilityFeedback: (token, previewId) => invoke('compatibility-discard', token, previewId),
  closeCompatibilityFeedback: token => invoke('compatibility-close', token),
  buildFeedback: (id, options = {}) => invoke('feedback-build', id, options),
  exportFeedback: (id, options = {}) => invoke('feedback-export', id, options),
  readNr: id => invoke('nr-read', id),
  writeNr: (id, patch) => invoke('nr-write', id, patch),
  readSrModel: id => invoke('sr-model-read', id),
  writeSrModel: (id, selection) => invoke('sr-model-write', id, selection),
  inspectLaunchSettings: id => invoke('launch-settings-inspect', id),
  updateLaunchSettings: (id, domain, request, options) => invoke('launch-settings-update', id, domain, request, options),
  resetAllLaunchSettings: id => invoke('launch-settings-reset-all', id),
  saveLaunchSettings: (id, domain, request) => invoke('launch-settings-save', id, domain, request),
  previewLaunchSettings: (id, domain, request) => invoke('launch-settings-preview', id, domain, request),
  applyLaunchSettings: (planId, consent) => invoke('launch-settings-apply', planId, consent),
  restoreLaunchSettings: (id, domain) => invoke('launch-settings-restore', id, domain),
  recoverLaunchSettings: id => invoke('launch-settings-recover', id),
  prepareFgComponents: (id, options) => invoke('fg-components-prepare', id, options),
  restoreFgComponents: id => invoke('fg-components-restore', id),
  recoverFgComponents: id => invoke('fg-components-recover', id),
  readReframework: id => invoke('game-reframework-inspect', id),
  prepareReframework: (id, options) => invoke('game-reframework-prepare', id, options),
  restoreReframework: id => invoke('game-reframework-restore', id),
  recoverReframework: id => invoke('game-reframework-recover', id),
  readHotkeys: id => invoke('game-hotkeys-read', id),
  writeHotkey: (id, target, binding) => invoke('game-hotkey-write', id, target, binding),
  restoreDefault: id => invoke('nr-default', id),
  recommended: id => invoke('nr-recommended', id),
  updateSettings: patch => invoke('settings-update', patch),
  listAddons: () => invoke('addon-list'),
  readPayloadSource: () => invoke('payload-source-read'),
  pickPayloadSource: () => invoke('payload-source-pick'),
  resetPayloadSource: () => invoke('payload-source-reset'),
  recheckPayloadSource: () => invoke('payload-source-recheck'),
  importAddon: file => invoke('addon-import', file),
  removeAddon: id => invoke('addon-remove', id),
  fetchGameArt: id => invoke('game-art', id),
  getGameIcon: (id, currentIcon) => invoke('game-icon', id, currentIcon),
  getExecutableIcon: file => invoke('game-selection-icon', file),
  confirmGame: selection => invoke('game-confirm', selection),
  pickGameIcon: () => invoke('pick-game-icon'),
  onAddonImported: callback => ipcRenderer.on('addon-imported', callback),
  onSrModelApplied: callback => ipcRenderer.on('sr-model-applied', (_event, payload) => callback(payload)),
  onLaunchSettingsApplied: callback => ipcRenderer.on('launch-settings-applied', (_event, payload) => callback(payload)),
  pathForFile: file => webUtils.getPathForFile(file),
  openExternal: key => invoke('open-external', key),
  openFolder: id => invoke('open-folder', id),
  copyText: text => invoke('copy-text', text),
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close')
}));
